import Head from "next/head";
import styles from "@/styles/Bets.module.css";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { useAccount, useConnect } from "wagmi";
import { Navbar } from "@/components/Navbar";
import { useEffect, useState } from "react";
import { AccountDetails } from "@/components/account/AccountDetails";
import { ADDRESS_ZERO } from "@/utils";

export default function Account() {
  const [selectedSection, setSelectedSection] = useState<number>(1);

  const connector = new MetaMaskConnector();
  const { connect, error, isLoading, pendingConnector } = useConnect();
  const { address } = useAccount({
    onConnect({ address }) {
      // @ts-ignore
      localStorage.setItem("connected", address);
    },
    // @ts-ignore
    onDisconnect({ address }) {
      // @ts-ignore
      localStorage.setItem("connected", ADDRESS_ZERO);
    },
  });

  useEffect(() => {
    let connected = localStorage.getItem("connected");
    console.log("CNCTD", connected);
    if (connected != ADDRESS_ZERO) connect({ connector });
  }, []);

  return (
    <>
      <Head>
        <title>Odds | Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.landingPage}>
        <Navbar />

        {/* bets bar */}
        <div className={styles.betsBar}>
          <p
            onClick={() => setSelectedSection(1)}
            className={
              selectedSection == 1 ? styles.selected : styles.notSelected
            }
          >
            Account Details
          </p>
          <p
            onClick={() => setSelectedSection(2)}
            className={
              selectedSection == 2 ? styles.selected : styles.notSelected
            }
          >
            My Bets
          </p>
        </div>

        {/* Handle The Selected Section */}

        {selectedSection == 1 && <AccountDetails />}
      </main>
    </>
  );
}
