import Head from "next/head";
import styles from "@/styles/Bets.module.css";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { useAccount, useConnect } from "wagmi";
import { Navbar } from "@/components/Navbar";
import { useState } from "react";
import { AccountDetails } from "@/components/account/AccountDetails";
import { MyBets } from "@/components/account/MyBets";

export default function Account() {
  const [selectedSection, setSelectedSection] = useState<number>(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.landingPage}>
        <Navbar />

        {/* bets bar */}
        <div className={styles.betsBar}>
          <p
            onClick={() => setSelectedSection(1)}
            className={
              selectedSection == 1 ? styles.selected : styles.notSelected
            }
          >
            Account Details
          </p>
          <p
            onClick={() => setSelectedSection(2)}
            className={
              selectedSection == 2 ? styles.selected : styles.notSelected
            }
          >
            My Bets
          </p>
        </div>

        {/* Handle The Selected Section */}

        {selectedSection == 1 && <AccountDetails />}

        {selectedSection == 2 && <MyBets />}
      </main>
    </>
  );
}
