import Head from "next/head";
import styles from "@/styles/Bets.module.css";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { useAccount, useConnect } from "wagmi";
import { Navbar } from "@/components/Navbar";
import { useState } from "react";
import { OpenBets } from "@/components/bets/OpenBets";
import { CompletedBets } from "@/components/bets/CompletedBets";
import { AwaitingValidatingBets } from "@/components/bets/Awaitingvalidation";
import { AwaitingAcceptance } from "@/components/bets/AwaitingAcceptance";
import { SearchBet } from "@/components/bets/SearchBet";

export default function Bets() {
  const [selectedSection, setSelectedSection] = useState<number>(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.landingPage}>
        <Navbar />

        {/* bets bar */}
        <div className={styles.betsBar}>
          <p
            onClick={() => setSelectedSection(1)}
            className={
              selectedSection == 1 ? styles.selected : styles.notSelected
            }
          >
            Open Bets
          </p>
          <p
            onClick={() => setSelectedSection(2)}
            className={
              selectedSection == 2 ? styles.selected : styles.notSelected
            }
          >
            Completed Bets
          </p>
          <p
            onClick={() => setSelectedSection(3)}
            className={
              selectedSection == 3 ? styles.selected : styles.notSelected
            }
          >
            Awaiting Validation
          </p>
          <p
            onClick={() => setSelectedSection(4)}
            className={
              selectedSection == 4 ? styles.selected : styles.notSelected
            }
          >
            Awaiting Acceptance
          </p>

          <p
            onClick={() => setSelectedSection(5)}
            className={
              selectedSection == 5 ? styles.selected : styles.notSelected
            }
          >
            Search Bet
          </p>
        </div>

        {/* Handle The Selected Section */}

        {selectedSection == 1 && <OpenBets />}

        {selectedSection == 2 && <CompletedBets />}

        {selectedSection == 3 && <AwaitingValidatingBets />}

        {selectedSection == 4 && <AwaitingAcceptance />}

        {selectedSection == 5 && <SearchBet />}
      </main>
    </>
  );
}
