import Head from "next/head";
import styles from "@/styles/Bets.module.css";
import { Navbar } from "@/components/Navbar";
import { useState } from "react";
import { BecomeAValidator } from "@/components/validators/BecomeAValidator";
import { AcceptRejectBet } from "@/components/validators/AcceptRejectBet";
import { ValidateBet } from "@/components/validators/ValidateBet";
import { ReportBet } from "@/components/validators/ReportBet";
import { Vote } from "@/components/validators/Vote";

export default function Validators() {
  const [selectedSection, setSelectedSection] = useState<number>(1);

  // TEST DATA

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.landingPage}>
        <Navbar />

        {/* bets bar */}
        <div className={styles.betsBar}>
          <p
            onClick={() => setSelectedSection(1)}
            className={
              selectedSection == 1 ? styles.selected : styles.notSelected
            }
          >
            Become A Validator
          </p>
          <p
            onClick={() => setSelectedSection(2)}
            className={
              selectedSection == 2 ? styles.selected : styles.notSelected
            }
          >
            Accept / Reject Bet
          </p>
          <p
            onClick={() => setSelectedSection(3)}
            className={
              selectedSection == 3 ? styles.selected : styles.notSelected
            }
          >
            Validate Bet
          </p>
          <p
            onClick={() => setSelectedSection(4)}
            className={
              selectedSection == 4 ? styles.selected : styles.notSelected
            }
          >
            Report Bet
          </p>
          <p
            onClick={() => setSelectedSection(5)}
            className={
              selectedSection == 5 ? styles.selected : styles.notSelected
            }
          >
            Vote
          </p>
        </div>

        {/* Handle The Selected Section */}

        {selectedSection == 1 && <BecomeAValidator />}

        {selectedSection == 2 && <AcceptRejectBet />}

        {selectedSection == 3 && <ValidateBet />}

        {selectedSection == 4 && <ReportBet />}

        {selectedSection == 5 && <Vote />}
      </main>
    </>
  );
}
